name: qm9-ml-env
channels:
  - conda-forge
  - rdkit
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - tensorflow
  - tensorflow-datasets
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - mordred
  - rdkit
  - pip
  - pip:
      - loguru
