name: QM9 ML Training Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up conda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: 3.10
          activate-environment: lsua_qm9
          environment-file: environment.yml
          use-mamba: true

      - name: Generate 2D and 3D descriptors
        run: |
          python scripts/compute_rdkit_descriptors.py
          python scripts/compute_full_mordred_descriptors.py

      - name: Train ML models
        run: python src/train_models.py

      - name: Upload results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: |
            results/metrics/
            results/plots/
            results/logs/
